variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  PROJECT_NAME: "callcentre-dashboard"
  PROJECT_COMPONENT: "data-service"
  DOCKER_PROJECT_NAME: "betalab-callcentre-dashboard"
  KUBERNETES_NAMESPACE: "project-callcentre"

before_script:
  - export TEST_PROFILE_NAME=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:=unstable}
  - export CI_MERGE_REQUEST_TARGET_BRANCH_NAME=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:=$CI_COMMIT_REF_NAME}

stages:
  - build
  - package

build:
  image: maven:3.8-amazoncorretto-17
  stage: build
  script:
    - mvn clean compile package
  rules:
    - if: $CI_COMMIT_TAG =~ /v[0-9]+\.[0-9]+\.[0-9]+/
      when: never
    - when: on_success

native-build:
  image: registry.docker.nat.bt.com/betalab-build-tools/maven-graalvm-17-native
  stage: build
  script:
    - mvn -Pnative clean compile package
  artifacts:
    paths:
      - target/dataservice
  rules:
    - if: $CI_COMMIT_TAG =~ /v[0-9]+\.[0-9]+\.[0-9]+/
      when: always
    - when: never

native-package:
  image: registry.docker.nat.bt.com/betalab-build-tools/bt-kaniko-build:latest
  stage: package
  script:
  - echo "{\"auths\":{\"https://registry.docker.nat.bt.com\":{\"username\":\"$DOCKER_REGISTRY_USER\",\"password\":\"$DOCKER_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --cache=false --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination=registry.docker.nat.bt.com/$DOCKER_PROJECT_NAME/$PROJECT_NAME:latest --destination=registry.docker.nat.bt.com/$DOCKER_PROJECT_NAME/$PROJECT_NAME:$CI_COMMIT_SHA
  rules:
    - if: $CI_COMMIT_TAG =~ /v[0-9]+\.[0-9]+\.[0-9]+/
      when: always
    - when: never
