#=======================================================================================
# Global Config
#=======================================================================================
spring:
  application:
    name: dataservice
  profiles:
    active: "dev"
  security:
    basic:
      enabled: false
    oauth2:
      client:
        registration:
          custom:
            authorization-grant-type: client_credentials
            client-id: callcentre-data-project
            client-secret: '112f8079-ff81-4092-8cd0-a4b6356da81f'
            provider: customprovider
        provider:
          customprovider:
            token-uri: https://keycloak.auth.betalab.rp.bt.com/auth/realms/master/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.auth.betalab.rp.bt.com/auth/realms/master

# Actuator endpoints
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /_/
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
  exposure.include: '*'
  cors:
    allowed-origins: '*'
    allowed-methods: GET,POST, PUT
    allowed-headers: '*'

dataservice:
  aiServiceUrl: SETINENV
---
#=======================================================================================
# Test Profile Config
#=======================================================================================
spring:
  profiles: test
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:dm;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    tomcat:
      initial-size: 1
server:
  port: 0
---
#=======================================================================================
# Development Profile Config
#=======================================================================================
spring:
  profiles: dev
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:dm;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    tomcat:
      initial-size: 1
server:
  port: 8080

dataservice:
  aiServiceUrl: http://callcenter.kubeflow-user-example-com.panoptes.uk/v2/models/callcenter/infer


---
#=======================================================================================
# Production ProfileConfig - ALL CONFIG SHOULD BE PASSED AS ENV VARIABLES
#=======================================================================================
spring:
  profiles: production
  datasource:
    url: NOTSET
    username: NOTSET
    password: NOTSET
    tomcat:
      initial-size: 1
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080